version: '3.7'

services:
  postgres:
    image: postgres:12.2
    environment:
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/c2s-project
    ports:
      - "3000:3000"
    depends_on:
      - postgres